In [16]:

# Creating Tensors

import tensorflow as tf
tensor = tf.constant([[1, 2], [3, 4]])
print(f"tensor:{tensor}")

# Variable Tensors
variable = tf.Variable([[1, 2], [3, 4]])
print(f"variable:{variable}")

# Basic Arithmetic Operations
# Addition

a = tf.constant([1, 2])
b = tf.constant([3, 4])
add_result = tf.add(a, b)  # Outputs [4, 6]
print(f"add_result:{add_result}")

# Subtraction
subtract_result = tf.subtract(a, b)  # Outputs [-2, -2]
print(f"subtract_result:{subtract_result}")

# Multiplication (Element-wise)
multiply_result = tf.multiply(a, b)  # Outputs [3, 8]
print(f"multiply_result:{multiply_result}")

# Division
divide_result = tf.divide(b, a)  # Outputs [3.0, 2.0]
print(f"divide_result:{divide_result}")

# Matrix Operations
# Matrix Multiplication
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[2, 0], [1, 2]])
matmul_result = tf.matmul(matrix1, matrix2)  # Outputs [[4, 4], [10, 8]]
print(f"matmul_result:{matmul_result}")

# Reshaping Tensors
# Reshape

tensor = tf.constant([1, 2, 3, 4, 5, 6])
reshaped_tensor = tf.reshape(tensor, [2, 3])  # Reshapes to 2x3 matrix
print(f"reshaped_tensor:{reshaped_tensor}")

# Aggregation Operations
# Sum
sum_result = tf.reduce_sum(tensor)  # Sums all elements
print(f"sum_result:{sum_result}")

# Max by row
sum_result2 = tf.reduce_sum(matrix1,axis=0)
print(f"sum_result2:{sum_result2}")

# Max by column
sum_result3 = tf.reduce_sum(matrix1,axis=1)
print(f"sum_result3:{sum_result3}")

# Max
max_result = tf.reduce_max(tensor)  # Finds the maximum value
print(f"max_result:{max_result}")



# Type Casting
# Cast
float_tensor = tf.cast(tensor, tf.float32)  # Casts integers to floats
print(f"float_tensor:{float_tensor}")

# Slicing and Indexing
# Slicing
sliced_tensor = tensor[1:3]  # Gets elements from index 1 to 2
print(f"sliced_tensor:{sliced_tensor}")



tensor:[[1 2]
 [3 4]]
variable:<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
add_result:[4 6]
subtract_result:[-2 -2]
multiply_result:[3 8]
divide_result:[3. 2.]
matmul_result:[[ 4  4]
 [10  8]]
reshaped_tensor:[[1 2 3]
 [4 5 6]]
sum_result:21
sum_result2:[4 6]
sum_result3:[3 7]
max_result:6
float_tensor:[1. 2. 3. 4. 5. 6.]
sliced_tensor:[2 3]


In [8]:
# Define a tensor
T1 = tf.Variable([1,2,3,4])

# Convert to numpy
N1 = T1.numpy()

print(f"T1: {T1}")
print(f"N1: {N1}")

T1: <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>
N1: [1 2 3 4]


In [9]:
# Create a tensor of shape [2, 3] filled with ones
ones_tensor = tf.ones([2, 3])
print("tf.ones example:")
print(ones_tensor)

tf.ones example:
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


### Using tf.ones_like

The tf.ones_like function creates a tensor with the same shape and datatype as an existing tensor, but fills it with ones. This is useful when you need a new tensor with the same size as another tensor but with all elements initialized to one.

In [10]:
# Assuming 'ones_tensor' from the previous example is defined
# Create a tensor of ones with the same shape as 'ones_tensor'
ones_like_tensor = tf.ones_like(ones_tensor)
print("tf.ones_like example:")
print(ones_like_tensor)

tf.ones_like example:
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


### tf.matmul

Function: tf.matmul is used for matrix multiplication. It performs the dot product between two tensors.
Input Requirements: Both tensors must be of rank 2 or higher (i.e., matrices or higher-dimensional arrays where matrix multiplication is defined along certain dimensions).
Use Case: This operation is commonly used in neural networks for performing linear transformations to the input data by weights, typical in layers of a deep learning model.

In [11]:
import tensorflow as tf

# Define two 2D tensors (matrices)
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result = tf.matmul(tensor1, tensor2)
print(result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


Matrix multiplication involves multiplying rows of the first matrix by columns of the second matrix and summing the products. Here's the step-by-step breakdown:

First element of the result matrix (Row 1, Column 1):
Multiply the elements of the first row of tensor1 with the first column of tensor2:
Calculation: 1×5+2×7=5+14=191×5+2×7=5+14=19

Second element of the result matrix (Row 1, Column 2):
Multiply the elements of the first row of tensor1 with the second column of tensor2:
Calculation: 1×6+2×8=6+16=221×6+2×8=6+16=22

Third element of the result matrix (Row 2, Column 1):
Multiply the elements of the second row of tensor1 with the first column of tensor2:
Calculation: 3×5+4×7=15+28=433×5+4×7=15+28=43

Fourth element of the result matrix (Row 2, Column 2):
Multiply the elements of the second row of tensor1 with the second column of tensor2:
Calculation: 3×6+4×8=18+32=503×6+4×8=18+32=50

$$
features = \begin{bmatrix} 2 & 24 \\ 2 & 26 \\ 2 & 57 \\ 1 & 37 \end{bmatrix}
bill = \begin{bmatrix} 3913 \\ 2682 \\ 8617 \\ 64400 \end{bmatrix}
params = \begin{bmatrix} 1000 \\ 150 \end{bmatrix}
$$

In [ ]:
# Define features, params, and bill as constants
features = tf.constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = tf.constant([[1000], [150]])
bill = tf.constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = tf.matmul(features,params)

# Compute and print the error
error = billpred - bill
print(error.numpy())

# Tensor rank

In [18]:
#scalar
a = tf.constant(1)
a

tf.Tensor(1, shape=(), dtype=int32)


In [19]:
#vector
b= tf.constant([1.2,2.3,3.4,4.5])
b

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.2, 2.3, 3.4, 4.5], dtype=float32)>

In [20]:
#matrix
c =tf.constant([[1,2],[3,4]])
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [21]:
#3-dimensional tensor
d=tf.constant([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
d


<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]], dtype=int32)>